In [1]:
import numpy

In [3]:
world_alcohol = numpy.genfromtxt('world_alcohol.txt', delimiter=',', dtype=str)
print(type(world_alcohol))
print(world_alcohol)
print(help(numpy.genfromtxt))

<class 'numpy.ndarray'>
[['Year' 'WHO region' 'Country' 'Beverage Types' 'Display Value']
 ['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]
Help on function genfromtxt in module numpy.lib.npyio:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=None, replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discar

In [6]:
vector = numpy.array([1,2,3,4])
print(vector.shape)
print(vector)
matrix = numpy.array([[1,2,3], [19,48,45], [33,34,56]])
print(matrix.shape)
print(matrix)

(4,)
[1 2 3 4]
(3, 3)
[[ 1  2  3]
 [19 48 45]
 [33 34 56]]


In [7]:
print(vector.dtype)

int64


In [8]:
vector = numpy.array([1,2,3,4.0])
print("numpy中只有同一种数据类型")
print(vector)
print(vector.dtype)

[1. 2. 3. 4.]
float64


In [11]:
world_alcohol = numpy.genfromtxt('world_alcohol.txt', delimiter=',', dtype=str, skip_header=1)
print(world_alcohol)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1987' 'Africa' 'Malawi' 'Other' '0.75']
 ['1989' 'Americas' 'Bahamas' 'Wine' '1.5']
 ['1985' 'Africa' 'Malawi' 'Spirits' '0.31']]


In [15]:
print("numpy中使用索引来取值")
first = world_alcohol[0,]
print(first)

numpy中使用索引来取值
['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']


In [16]:
America_1986_Uruguay = world_alcohol[1,3]
print(America_1986_Uruguay)

Other


In [17]:
vector = numpy.array([1,2,3,4.0])
print(vector)
print("对array进行算数操作,会对array中的每个元素进行操作")
vector == 10

[1. 2. 3. 4.]
对array进行算数操作,会对array中的每个元素进行操作


array([False, False, False, False])

In [18]:
vector * 10

array([10., 20., 30., 40.])

In [19]:
vector + 2

array([3., 4., 5., 6.])